/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup HoTTBridgeStatus HoTTBridgeStatus
 * @brief HoTTBridge Status Information
 *
 * Autogenerated files and functions for HoTTBridgeStatus Object
 *
 * @{
 *
 * @file       hottbridgestatus.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the HoTTBridgeStatus object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: hottbridgestatus.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef HOTTBRIDGESTATUS_H
#define HOTTBRIDGESTATUS_H
#include <stdbool.h>
/* Object constants */
#define HOTTBRIDGESTATUS_OBJID 0x860C5F84
#define HOTTBRIDGESTATUS_ISSINGLEINST 1
#define HOTTBRIDGESTATUS_ISSETTINGS 0
#define HOTTBRIDGESTATUS_ISPRIORITY 1
#define HOTTBRIDGESTATUS_NUMBYTES sizeof(HoTTBridgeStatusData)

/* Field TxPackets information */

/* Field RxPackets information */

/* Field TxFail information */

/* Field RxFail information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    uint32_t TxPackets;
    uint32_t RxPackets;
    uint32_t TxFail;
    uint32_t RxFail;

} __attribute__((packed)) HoTTBridgeStatusDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef HoTTBridgeStatusDataPacked __attribute__((aligned(4))) HoTTBridgeStatusData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    HoTTBridgeStatusDataPacked data;
    byte arr[HOTTBRIDGESTATUS_NUMBYTES];
 } HoTTBridgeStatusDataUnion;

#endif // HOTTBRIDGESTATUS_H

/**
 * @}
 * @}
 */
